export const environment = {
  production: false,
  cotasApiBase: '/cotas-api',
  galleryApiBase: '/gallery-api',
  galleryToken: 'REPLACE_WITH_GALLERY_TOKEN',
  kontaktApiBase: '/kontakt-api',
  kontaktToken: 'REPLACE_WITH_KONTAKT_TOKEN',
  joomlaApiBase: '/joomla-api/api/index.php/v1',
  joomlaToken: 'REPLACE_WITH_JOOMLA_TOKEN',
  joomlaCategoryFaq: 9,
  joomlaCategoryNews: 8,
  joomlaCategoryTeam: 13,
  joomlaCategoryVeranstaltungen: 14,
  joomlaImageBase: 'https://joomla.tanzschule-family-and-friends.de',
  mediaBaseUrl: 'https://video.tsfaf.de/v2/Webseite',
};
